services:
  db:
    image: postgres:16-alpine
    container_name: bank2xml-postgres-db

    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    expose:
      - "5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - bank2xml


  backend:
    build:
      context: ./backend
    container_name: bank2xml-backend

    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy

    environment:
      PGQL_URL: ${PGQL_URL}
      CORS_ORIGIN: ${CORS_ORIGIN}
      CORS_ORIGIN_2: ${CORS_ORIGIN_2}
      CORS_ORIGIN_3: ${CORS_ORIGIN_3}
      CORS_ORIGIN_4: ${CORS_ORIGIN_4}

      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      ACCESS_TOKEN_EXPIRY: ${ACCESS_TOKEN_EXPIRY}

      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      REFRESH_TOKEN_EXPIRY: ${REFRESH_TOKEN_EXPIRY}

      ALGO: ${ALGO}

      SESSION_SECRET: ${SESSION_SECRET}

      RESENDER_API_KEY: ${RESENDER_API_KEY}
      RESENDER_DOMAIN: ${RESENDER_DOMAIN}

      ADMIN_MAIL_ADDRESS: ${ADMIN_MAIL_ADDRESS}

      RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID}
      RAZORPAY_KEY_SECRET: ${RAZORPAY_KEY_SECRET}
      RAZORPAY_WEBHOOK_SECRET: ${RAZORPAY_WEBHOOK_SECRET}

      REDISS_URL: ${REDISS_URL}
    
    ports:
      - "8000:8000"

    expose:
      - "8000"

    networks:
      - bank2xml
    
    volumes:
      - shared_uploads:/app/uploads
      - shared_outputs:/app/outputs

  rediss:
    image: redis:7-alpine
    container_name: bank2xml-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - bank2xml
  
  celery:
    build:
      context: ./backend
    environment:
      REDISS_URL: ${REDISS_URL}
      PGQL_URL: ${PGQL_URL}
    command: celery -A app.tasks.celery:celery_app worker --loglevel=info --concurrency=2
    volumes:
      - ./backend:/app
      - shared_uploads:/app/uploads
      - shared_outputs:/app/outputs
    depends_on:
      - rediss
      - db
    networks:
      - bank2xml

  frontend:
    build:
      context: ./app
    container_name: bank2xml-frontend

    restart: unless-stopped

    depends_on:
      - backend
    
    ports:
      - "3000:3000"

    expose:
      - "3000"

    networks:
      - bank2xml


volumes:
  postgres_data:
  shared_uploads:
  shared_outputs:


networks:
  bank2xml:
